"""Built-in rules. Each rule targets a well-known, high-signal pattern; the AI pass handles nuance."""

from __future__ import annotations

import re

from codeview.models import Category, Severity
from codeview.rules.engine import Rule

C, H, M, L, N = Severity.CRITICAL, Severity.HIGH, Severity.MEDIUM, Severity.LOW, Severity.INFO
SEC, BUG, PERF, MAINT, TEST = (
    Category.SECURITY,
    Category.BUG,
    Category.PERFORMANCE,
    Category.MAINTAINABILITY,
    Category.TESTING,
)

PY = frozenset({"python"})
JS = frozenset({"javascript", "typescript", "vue", "svelte", "html"})
TS = frozenset({"typescript"})
GO = frozenset({"go"})
WORKFLOWS = (".github/workflows/*.yml", ".github/workflows/*.yaml", "action.yml", "action.yaml")

_PLACEHOLDER = re.compile(
    r"(?i)(example|sample|changeme|change_me|dummy|placeholder|your[_-]|xxxx|\*\*\*|<[^>]+>|\$\{|\{\{|%\(|"
    r"os\.environ|getenv|process\.env|env\(|redacted|test|fake|mock)"
)


def _r(
    id: str,
    title: str,
    severity: Severity,
    category: Category,
    pattern: str,
    message: str,
    *,
    suggestion: str | None = None,
    cwe: str | None = None,
    languages: frozenset[str] | None = None,
    paths: tuple[str, ...] = (),
    secret: bool = False,
    skip_tests: bool = False,
    ignore_if: re.Pattern[str] | None = None,
    flags: int = 0,
) -> Rule:
    return Rule(
        id=id,
        title=title,
        severity=severity,
        category=category,
        pattern=re.compile(pattern, flags),
        message=message,
        suggestion=suggestion,
        cwe=cwe,
        languages=languages,
        paths=paths,
        secret=secret,
        skip_tests=skip_tests,
        ignore_if=ignore_if,
    )


_ROTATE = "Remove it from the change, rotate the credential immediately (it is now in git history) and load it from a secret manager or environment variable."

BUILTIN_RULES: list[Rule] = [
    # Secrets
    _r(
        "CV-SEC-001",
        "AWS access key committed",
        C,
        SEC,
        r"\b(?:AKIA|ASIA)[0-9A-Z]{16}\b",
        "An AWS access key id appears in the diff.",
        suggestion=_ROTATE,
        cwe="CWE-798",
        secret=True,
    ),
    _r(
        "CV-SEC-002",
        "GitHub token committed",
        C,
        SEC,
        r"\b(?:ghp|gho|ghu|ghs|ghr)_[A-Za-z0-9]{36,}\b|\bgithub_pat_[A-Za-z0-9_]{50,}\b",
        "A GitHub access token appears in the diff.",
        suggestion=_ROTATE,
        cwe="CWE-798",
        secret=True,
    ),
    _r(
        "CV-SEC-003",
        "Private key committed",
        C,
        SEC,
        r"-----BEGIN (?:RSA |EC |DSA |OPENSSH |PGP |ENCRYPTED )?PRIVATE KEY(?: BLOCK)?-----",
        "A private key block appears in the diff.",
        suggestion=_ROTATE,
        cwe="CWE-321",
    ),
    _r(
        "CV-SEC-004",
        "Slack token committed",
        C,
        SEC,
        r"\bxox[abposr]-[A-Za-z0-9-]{10,}\b",
        "A Slack token appears in the diff.",
        suggestion=_ROTATE,
        cwe="CWE-798",
        secret=True,
    ),
    _r(
        "CV-SEC-005",
        "Stripe live key committed",
        C,
        SEC,
        r"\b(?:sk|rk)_live_[A-Za-z0-9]{20,}\b",
        "A live Stripe secret key appears in the diff.",
        suggestion=_ROTATE,
        cwe="CWE-798",
        secret=True,
    ),
    _r(
        "CV-SEC-006",
        "Google API key committed",
        H,
        SEC,
        r"\bAIza[0-9A-Za-z_-]{35}\b",
        "A Google API key appears in the diff.",
        suggestion=_ROTATE,
        cwe="CWE-798",
        secret=True,
    ),
    _r(
        "CV-SEC-007",
        "AI provider API key committed",
        C,
        SEC,
        r"\b(?:sk-(?:proj-|ant-(?:api\d{2}-)?|or-v1-)[A-Za-z0-9_-]{32,}|gsk_[A-Za-z0-9]{40,}|csk-[A-Za-z0-9]{40,})\b",
        "An API key for an AI/LLM provider appears in the diff.",
        suggestion=_ROTATE,
        cwe="CWE-798",
        secret=True,
    ),
    _r(
        "CV-SEC-008",
        "Hard-coded credential",
        H,
        SEC,
        r"""(?i)(?<![a-z0-9])(?:password|passwd|pwd|secret|api[_-]?key|access[_-]?token|auth[_-]?token|client[_-]?secret|private[_-]?key)\w*["']?\s*[:=]\s*["'][^"'\s]{8,}["']""",
        "A credential-like value is assigned a string literal.",
        suggestion="Read secrets from the environment or a secret manager instead of hard-coding them.",
        cwe="CWE-798",
        secret=True,
        skip_tests=True,
        ignore_if=_PLACEHOLDER,
    ),
    _r(
        "CV-SEC-009",
        "Credentials embedded in URL",
        H,
        SEC,
        r"\b[a-z][a-z0-9+.-]{1,20}://[^\s:/@'\"]{1,64}:[^\s@/'\"]{3,}@[\w.-]+",
        "A connection URL contains an inline username and password.",
        suggestion="Move the password to an environment variable or secret store.",
        cwe="CWE-798",
        secret=True,
        skip_tests=True,
        ignore_if=_PLACEHOLDER,
    ),
    _r(
        "CV-SEC-010",
        "JSON Web Token committed",
        H,
        SEC,
        r"\beyJ[A-Za-z0-9_-]{10,}\.eyJ[A-Za-z0-9_-]{10,}\.[A-Za-z0-9_-]{10,}",
        "A JWT appears in the diff; it may grant access until it expires.",
        suggestion=_ROTATE,
        cwe="CWE-798",
        secret=True,
        skip_tests=True,
    ),
    # Injection & dangerous APIs
    _r(
        "CV-SEC-020",
        "Dynamic code execution",
        H,
        SEC,
        r"(?<![\w.])(?<!def\s)(?:eval|exec)\s*\(",
        "eval()/exec() runs arbitrary code; with any user-influenced input this is remote code execution.",
        suggestion="Use ast.literal_eval, json.loads or an explicit dispatch table.",
        cwe="CWE-95",
        languages=PY,
    ),
    _r(
        "CV-SEC-021",
        "Dynamic code execution",
        H,
        SEC,
        r"(?<![\w.])eval\s*\(|\bnew\s+Function\s*\(",
        "eval()/new Function() execute strings as code.",
        suggestion="Parse data with JSON.parse or use a lookup table.",
        cwe="CWE-95",
        languages=JS,
    ),
    _r(
        "CV-SEC-022",
        "Shell command injection risk",
        H,
        SEC,
        r"\bshell\s*=\s*True\b",
        "subprocess with shell=True passes the command through a shell; untrusted input leads to command injection.",
        suggestion="Pass an argument list and keep shell=False.",
        cwe="CWE-78",
        languages=PY,
    ),
    _r(
        "CV-SEC-023",
        "Shell command execution",
        M,
        SEC,
        r"\bos\.(?:system|popen)\s*\(|\bcommands\.getoutput\s*\(",
        "os.system/os.popen run commands through a shell.",
        suggestion="Use subprocess.run([...], check=True) with an argument list.",
        cwe="CWE-78",
        languages=PY,
    ),
    _r(
        "CV-SEC-024",
        "Shell command execution",
        M,
        SEC,
        r"\bexecSync\s*\(|\bchild_process\.exec\s*\(|\bRuntime\.getRuntime\(\)\.exec\s*\(|\b(?:shell_exec|passthru|system|proc_open)\s*\(\s*\$",
        "A shell command is built and executed; make sure no untrusted input reaches it.",
        suggestion="Prefer execFile/spawn with an argument array (or ProcessBuilder) over shell strings.",
        cwe="CWE-78",
    ),
    _r(
        "CV-SEC-025",
        "SQL built from strings",
        H,
        SEC,
        r"""(?ix)(?:\bf["']|`)\s*(?:SELECT|INSERT|UPDATE|DELETE|DROP|MERGE)\b[^"'`]*(?:\{|\$\{)"""
        r"""|["'`]\s*(?:SELECT\s.+?\sFROM|INSERT\s+INTO|UPDATE\s+\w+\s+SET|DELETE\s+FROM)\b[^"'`]*["'`]\s*(?:\+|%\s*[\w(]|\.format\()"""
        r"""|\bSprintf\(\s*"(?:SELECT|INSERT|UPDATE|DELETE)\b""",
        "A SQL statement is assembled with string formatting or concatenation, which enables SQL injection.",
        suggestion="Use parameterised queries / bound parameters provided by your driver or ORM.",
        cwe="CWE-89",
    ),
    _r(
        "CV-SEC-026",
        "Unsafe deserialization",
        H,
        SEC,
        r"\b(?:pickle|cPickle|dill|marshal|shelve)\.loads?\s*\(|\bjsonpickle\.decode\s*\(|\byaml\.(?:unsafe_)?load\s*\((?![^)]*Safe)|\byaml\.load_all\s*\((?![^)]*Safe)",
        "Deserializing untrusted data with pickle/marshal/unsafe YAML can execute arbitrary code.",
        suggestion="Use json, or yaml.safe_load for YAML.",
        cwe="CWE-502",
        languages=PY,
    ),
    _r(
        "CV-SEC-027",
        "Unsafe deserialization",
        H,
        SEC,
        r"\bnew\s+ObjectInputStream\s*\(|\bunserialize\s*\(\s*\$|\bBinaryFormatter\b",
        "Native object deserialization of untrusted data can lead to remote code execution.",
        suggestion="Use a data-only format such as JSON with an explicit schema.",
        cwe="CWE-502",
    ),
    _r(
        "CV-SEC-028",
        "TLS certificate verification disabled",
        H,
        SEC,
        r"\bverify\s*=\s*False\b|\brejectUnauthorized\s*:\s*false\b|\bInsecureSkipVerify\s*:\s*true\b|NODE_TLS_REJECT_UNAUTHORIZED\s*=\s*['\"]?0|\bCERT_NONE\b|curl\s[^\n]*\s(?:-k|--insecure)\b",
        "Certificate verification is turned off, allowing man-in-the-middle attacks.",
        suggestion="Keep verification on; configure a custom CA bundle if you need one.",
        cwe="CWE-295",
    ),
    _r(
        "CV-SEC-029",
        "Weak hash algorithm",
        M,
        SEC,
        r"\bhashlib\.(?:md5|sha1)\s*\((?![^)]*usedforsecurity\s*=\s*False)|\bcreateHash\(\s*['\"](?:md5|sha1)['\"]|\bMessageDigest\.getInstance\(\s*\"(?:MD5|SHA-?1)\"|\bmd5\.New\(|\bsha1\.New\(",
        "MD5/SHA-1 are broken for security purposes (passwords, signatures, integrity).",
        suggestion="Use SHA-256+ for integrity and a password hash (argon2, bcrypt, scrypt) for passwords.",
        cwe="CWE-327",
    ),
    _r(
        "CV-SEC-030",
        "Cross-site scripting sink",
        M,
        SEC,
        r"\.(?:inner|outer)HTML\s*[+]?=(?!=)|\bdangerouslySetInnerHTML\b|\bdocument\.write(?:ln)?\s*\(|\bv-html\s*=|\{@html\s|\binsertAdjacentHTML\s*\(|\bbypassSecurityTrust\w+\s*\(",
        "Raw HTML is injected into the page; unsanitised input here is a cross-site scripting vulnerability.",
        suggestion="Render text with textContent / framework bindings, or sanitise with DOMPurify.",
        cwe="CWE-79",
    ),
    _r(
        "CV-SEC-031",
        "Auto-escaping disabled",
        M,
        SEC,
        r"\bmark_safe\s*\(|\|\s*safe\b|\bMarkup\s*\(|autoescape\s*=\s*False",
        "HTML auto-escaping is bypassed; make sure the value can never contain user input.",
        suggestion="Escape values explicitly or keep auto-escaping on.",
        cwe="CWE-79",
        languages=PY | {"html"},
    ),
    _r(
        "CV-SEC-032",
        "Insecure randomness for secrets",
        M,
        SEC,
        r"(?i)(?:token|secret|password|passwd|nonce|salt|otp|api_?key)\w*\s*=.*(?:\brandom\.(?:random|randint|choice|choices|getrandbits|randrange)\(|\bMath\.random\(\))",
        "A non-cryptographic random generator is used for a security-sensitive value.",
        suggestion="Use secrets.token_urlsafe / crypto.randomUUID / crypto.getRandomValues.",
        cwe="CWE-338",
    ),
    _r(
        "CV-SEC-033",
        "Permissive CORS policy",
        M,
        SEC,
        r"""(?i)Access-Control-Allow-Origin["']?\s*[:,]\s*["']\*|allow_origins\s*=\s*\[\s*["']\*["']|\bcors\(\s*\)|origin\s*:\s*["']\*["']""",
        "CORS allows any origin; combined with credentials this exposes authenticated endpoints.",
        suggestion="Allow-list the exact origins that need access.",
        cwe="CWE-942",
    ),
    _r(
        "CV-SEC-034",
        "Debug mode enabled",
        M,
        SEC,
        r"^\s*DEBUG\s*=\s*True\b|\.run\([^)]*\bdebug\s*=\s*True",
        "Debug mode exposes stack traces and, in some frameworks, an interactive console.",
        suggestion="Drive debug mode from an environment variable that is off in production.",
        cwe="CWE-489",
        languages=PY,
        skip_tests=True,
    ),
    _r(
        "CV-SEC-035",
        "World-writable permissions",
        M,
        SEC,
        r"\bchmod\s+(?:-R\s+)?0?777\b|\bchmod\([^)]*0o?777\b|\bMode\(0?777\)",
        "Files are made writable by every user on the system.",
        suggestion="Grant the minimum permissions needed (e.g. 0o640 / 0o750).",
        cwe="CWE-732",
    ),
    _r(
        "CV-SEC-036",
        "Remote script piped to shell",
        M,
        SEC,
        r"\b(?:curl|wget)\b[^|\n]*\|\s*(?:sudo\s+)?(?:ba|z)?sh\b",
        "A script is downloaded and executed without integrity verification.",
        suggestion="Download, verify a checksum or signature, then execute.",
        cwe="CWE-494",
    ),
    _r(
        "CV-SEC-037",
        "Path traversal risk",
        M,
        SEC,
        r"\bsend_file\s*\(\s*(?:request\.|f[\"'])|\bres\.sendFile\s*\(\s*req\.|\bopen\s*\(\s*(?:request\.|req\.)",
        "A file path is taken from request data; '../' sequences may escape the intended directory.",
        suggestion="Resolve the path and verify it stays inside an allowed base directory.",
        cwe="CWE-22",
    ),
    _r(
        "CV-SEC-038",
        "Server-side request forgery risk",
        M,
        SEC,
        r"\b(?:requests|httpx)\.(?:get|post|put|delete|request)\s*\(\s*(?:request\.|f[\"']https?://\{)|\bfetch\s*\(\s*req\.(?:query|body|params)",
        "An outbound request URL comes from user input.",
        suggestion="Validate the URL against an allow-list of hosts and block private address ranges.",
        cwe="CWE-918",
    ),
    # CI/CD supply chain
    _r(
        "CV-SEC-050",
        "Workflow runs on pull_request_target",
        H,
        SEC,
        r"^\s*(?:-\s*)?pull_request_target\s*:?",
        "pull_request_target runs with repository secrets and write permissions; checking out or running PR code here is dangerous.",
        suggestion="Use pull_request, or never check out / execute the PR's head in this workflow.",
        cwe="CWE-829",
        paths=WORKFLOWS,
    ),
    _r(
        "CV-SEC-051",
        "Script injection in workflow",
        H,
        SEC,
        r"\$\{\{\s*github\.(?:event\.(?:issue|pull_request|comment|review|review_comment|discussion|head_commit|commits|pages)[\w.\[\]*]*\.(?:title|body|message|name|label|ref|email|default_branch|page_name)|head_ref)\s*\}\}",
        "Attacker-controlled event data is interpolated directly into the workflow, enabling command injection in `run:` steps.",
        suggestion='Pass the value through an environment variable (env: TITLE: ${{ ... }}) and quote "$TITLE" in the script.',
        cwe="CWE-94",
        paths=WORKFLOWS,
    ),
    _r(
        "CV-SEC-052",
        "Action pinned to a moving branch",
        L,
        SEC,
        r"\buses:\s*[\w.-]+/[\w./-]+@(?:main|master|dev|latest)\s*$",
        "The action is pinned to a branch, so upstream changes run in your CI without review.",
        suggestion="Pin to a release tag or, better, a full commit SHA.",
        cwe="CWE-829",
        paths=WORKFLOWS,
    ),
    _r(
        "CV-SEC-053",
        "Over-broad workflow permissions",
        M,
        SEC,
        r"^\s*permissions\s*:\s*write-all\b",
        "The workflow token is granted write access to everything.",
        suggestion="Grant only the scopes each job needs.",
        cwe="CWE-250",
        paths=WORKFLOWS,
    ),
    _r(
        "CV-SEC-054",
        "Unpinned container base image",
        L,
        SEC,
        r"(?i)^\s*FROM\s+(?:[^\s:@]+|\S+:latest)(?:\s+AS\s+\w+)?\s*$",
        "The base image uses an implicit or 'latest' tag, making builds non-reproducible.",
        suggestion="Pin a version tag (ideally plus @sha256 digest).",
        languages=frozenset({"dockerfile"}),
    ),
    # Bugs
    _r(
        "CV-BUG-001",
        "Bare except",
        M,
        BUG,
        r"^\s*except\s*:",
        "A bare except also catches KeyboardInterrupt and SystemExit and hides real errors.",
        suggestion="Catch the specific exceptions you expect (or at least `except Exception:`).",
        languages=PY,
    ),
    _r(
        "CV-BUG-002",
        "Exception silently swallowed",
        L,
        BUG,
        r"^\s*except\b[^:]*:\s*(?:pass|\.\.\.)\s*(?:#.*)?$",
        "The exception is swallowed without logging, which makes failures invisible.",
        suggestion="Log the exception or narrow what is caught and explain why it is safe to ignore.",
        languages=PY,
    ),
    _r(
        "CV-BUG-003",
        "Mutable default argument",
        M,
        BUG,
        r"\bdef\s+\w+\s*\([^)]*=\s*(?:\[\s*\]|\{\s*\}|set\(\s*\)|dict\(\s*\)|list\(\s*\))",
        "Default values are evaluated once, so the mutable default is shared between calls.",
        suggestion="Default to None and create the container inside the function.",
        languages=PY,
    ),
    _r(
        "CV-BUG-004",
        "Comparison to None with ==",
        L,
        BUG,
        r"[=!]=\s*None\b",
        "Use `is None` / `is not None`; `==` can be overridden and behaves unexpectedly.",
        languages=PY,
    ),
    _r(
        "CV-BUG-005",
        "Empty catch block",
        L,
        BUG,
        r"\bcatch\s*(?:\([^)]*\))?\s*\{\s*\}",
        "Errors are caught and discarded silently.",
        suggestion="Handle, log or rethrow the error.",
        languages=JS | frozenset({"java", "csharp", "kotlin", "php"}),
    ),
    # Leftovers & maintainability
    _r(
        "CV-QUAL-001",
        "Debugger statement left in",
        M,
        MAINT,
        r"^\s*(?:breakpoint\(\)|import\s+i?pdb\b|i?pdb\.set_trace\(\))",
        "A debugger hook will pause execution in production.",
        suggestion="Remove it before merging.",
        languages=PY,
    ),
    _r(
        "CV-QUAL-002",
        "Debugger statement left in",
        M,
        MAINT,
        r"^\s*debugger\s*;?\s*$",
        "A `debugger` statement will pause execution when dev tools are open.",
        suggestion="Remove it before merging.",
        languages=JS,
    ),
    _r(
        "CV-QUAL-003",
        "Console logging left in",
        L,
        MAINT,
        r"\bconsole\.(?:log|debug|trace)\s*\(",
        "Leftover console logging adds noise and can leak data.",
        suggestion="Remove it or use the project's logger.",
        languages=JS,
        skip_tests=True,
    ),
    _r(
        "CV-QUAL-004",
        "Focused or skipped test",
        M,
        TEST,
        r"\b(?:it|describe|test|context)\.only\s*\(|(?<![\w.])f(?:it|describe)\s*\(",
        "`.only` makes the runner skip every other test in CI.",
        suggestion="Remove `.only` before merging.",
        languages=JS,
    ),
    _r(
        "CV-QUAL-005",
        "Type checking bypassed",
        L,
        MAINT,
        r"@ts-ignore\b|:\s*any\b|\bas\s+any\b",
        "`any`/`@ts-ignore` switch off type checking for this code.",
        suggestion="Use a precise type, `unknown` with narrowing, or `@ts-expect-error` with a reason.",
        languages=TS,
    ),
    _r(
        "CV-QUAL-006",
        "TODO / FIXME added",
        N,
        MAINT,
        r"\b(?:TODO|FIXME|HACK|XXX)\b(?!\s*\()",
        "New TODO/FIXME left in the code.",
        suggestion="Track it in an issue and reference the issue number.",
    ),
    _r(
        "CV-QUAL-007",
        "Unchecked unwrap",
        N,
        BUG,
        r"\.unwrap\(\)",
        "`.unwrap()` panics on None/Err.",
        suggestion="Propagate with `?` or handle the error case explicitly.",
        languages=frozenset({"rust"}),
        skip_tests=True,
    ),
    _r(
        "CV-QUAL-008",
        "Error ignored",
        L,
        BUG,
        r"^\s*_\s*(?:,\s*_\s*)?=\s*\w[\w.]*\(|,\s*_\s*:?=\s*\w[\w.]*\(.*\berr",
        "An error return value is discarded.",
        suggestion="Handle or explicitly wrap the error.",
        languages=GO,
    ),
    _r(
        "CV-PERF-001",
        "SELECT *",
        L,
        PERF,
        r"(?i)\bSELECT\s+\*\s+FROM\b",
        "SELECT * fetches every column, breaks when the schema changes and prevents covering indexes.",
        suggestion="Select only the columns you need.",
        skip_tests=True,
    ),
]
