name: daily-reviewgenie
on:
  schedule:
    - cron: "0 9 * * *"   # 09:00 UTC
jobs:
  sweep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: {python-version: '3.11'}
      - run: |
          pip install -r requirements.txt
          python -m codeview_mcp.cli analyze https://github.com/mann-uofg/example-sandbox/pull/1
